# Generated by Django 5.2.8 on 2026-06-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPanchangAlmanac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_city', models.CharField(db_index=True, max_length=150)),
                ('resolved_country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('iana_timezone', models.CharField(max_length=100)),
                ('calculation_date', models.DateField(db_index=True)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('moonrise', models.CharField(max_length=50)),
                ('moonset', models.CharField(max_length=50)),
                ('sun_sign', models.CharField(max_length=50)),
                ('moon_sign', models.CharField(max_length=50)),
                ('abhijeet_muhurat_start', models.TimeField()),
                ('abhijeet_muhurat_end', models.TimeField()),
                ('rahu_kaal_start', models.TimeField()),
                ('rahu_kaal_end', models.TimeField()),
                ('shaka_samvat', models.IntegerField()),
                ('vikram_samvat', models.IntegerField()),
                ('var_day_name', models.CharField(max_length=20)),
                ('paksha', models.CharField(max_length=20)),
                ('ananta_month', models.CharField(max_length=50)),
                ('purnima_month', models.CharField(max_length=50)),
                ('pravisthe_gate', models.IntegerField()),
                ('tithi_timeline', models.CharField(max_length=150)),
                ('nakshatra_timeline', models.CharField(max_length=150)),
                ('yoga_timeline', models.CharField(max_length=150)),
                ('karana_timeline', models.CharField(max_length=150)),
            ],
            options={
                'indexes': [models.Index(fields=['calculation_date', 'requested_city'], name='idx_date_city_composite')],
                'unique_together': {('calculation_date', 'requested_city')},
            },
        ),
    ]
